swent-group10/polyfit

.gitignore
README.md

1. Adding the readme file alongside the project figma link.
2. Add DS_Store to the git ignore

README Creation and gitignore updates

---

.github/workflows/ci.yml
app/build.gradle.kts

Added a modified CI pipeline inspired from the template and added the requirements in the gradle app file for SonarCloud

Add Pipeline implementation

---

app/src/main/java/com/github/se/polyfit/README.md

First attempt on how to use Material3

Create README.md for material3

---

settings.gradle.kts

Solving issues me, ben, sharif had with Gradle by fixing the name of the root project

Fixed Capitalization for project settings

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/NutritionalInformationTest.kt
app/src/main/java/com/github/se/polyfit/ui/components/AddIngredientPopup.kt
app/src/main/java/com/github/se/polyfit/ui/screen/NutritionScreen.kt
app/src/main/java/com/github/se/polyfit/viewmodel/meal/MealViewModel.kt
app/src/test/java/com/github/se/polyfit/viewmodel/meal/MealViewModelTest.kt

Fixing the double addition of nutritional value and the state for isComplete

Bugfix: Nutritional value and isComplete

---

app/src/androidTest/java/com/github/se/polyfit/data/api/SpoonacularApiCallerTest.kt
app/src/androidTest/java/com/github/se/polyfit/data/remote/firebase/MealFirebaseRepositoryTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt

https://github.com/swent-group10/polyfit/issues/116
There are a handful of warnings in our console when running tests (see issue above for exact). Cleaning this warnings up now so that our logs are clean and we can easily detect real errors.

FIX: Console Warnings

---

app/src/test/java/com/github/se/polyfit/viewmodel/meal/MealViewModelTest.kt

In the sake of M1, we skipped some testing. Adding that coverage now (and thanks to @aprilslis for figuring out how to test this :D) 
Ticket: https://github.com/swent-group10/polyfit/issues/107

Add missing tests for MealViewModel

---

app/src/androidTest/java/com/github/se/polyfit/data/local/database/MealDatabaseTest.kt
app/src/main/java/com/github/se/polyfit/data/local/database/MealDatabase.kt
app/src/main/java/com/github/se/polyfit/data/local/entity/MealEntity.kt
app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt
app/src/main/java/com/github/se/polyfit/model/meal/MealTag.kt
app/src/test/java/com/github/se/polyfit/model/meal/MealTagTest.kt
app/src/test/java/com/github/se/polyfit/model/meal/MealTest.kt

We have decided to add tags to each meal creation to put labels like "pet-friendly" or "nut allergy warning" to the meals we create. This PR created a new data class called `MealTag` and the `Meal` data class has a new field that records the tags it has.

Add Meal Tags

---

app/src/androidTest/java/com/github/se/polyfit/ui/components/button/PrimaryPurpleButtonScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/button/PrimaryPurpleButtonTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/dialog/AddIngredientPopupTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/dialog/AddIngredientScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/ingredients/IngredientNutritionEditFieldsScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/ingredients/IngredientNutritionEditFieldsTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/nutrition/NutritionalInformationScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/nutrition/NutritionalInformationTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/scaffold/BottomNavigationBarScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/scaffold/BottomNavigationBarTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/utils/FunctionalityNotAvailablePopupTest.kt
app/src/main/java/com/github/se/polyfit/ui/components/GenericScreen.kt
app/src/main/java/com/github/se/polyfit/ui/components/button/GradientButton.kt
app/src/main/java/com/github/se/polyfit/ui/components/button/PrimaryPurpleButton.kt
app/src/main/java/com/github/se/polyfit/ui/components/dialog/AddIngredientPopup.kt
app/src/main/java/com/github/se/polyfit/ui/components/dialog/FunctionalityNotAvailablePopup.kt
app/src/main/java/com/github/se/polyfit/ui/components/dialog/PictureDialog.kt
app/src/main/java/com/github/se/polyfit/ui/components/ingredients/IngredientList.kt
app/src/main/java/com/github/se/polyfit/ui/components/ingredients/IngredientNutritionEditFields.kt
app/src/main/java/com/github/se/polyfit/ui/components/nutrition/NutritionalInformation.kt
app/src/main/java/com/github/se/polyfit/ui/components/scaffold/AppTitleTopBar.kt
app/src/main/java/com/github/se/polyfit/ui/components/scaffold/BottomNavigation.kt
app/src/main/java/com/github/se/polyfit/ui/screen/IngredientScreen.kt
app/src/main/java/com/github/se/polyfit/ui/screen/NutritionScreen.kt
app/src/main/java/com/github/se/polyfit/ui/screen/OverviewScreen.kt

Our components are getting to be a long list, adding some more folders to segment and make it easier to find files.

Add folder structure for UI components

---

app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealOccasionSelectorScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealOccasionSelectorTest.kt
app/src/main/java/com/github/se/polyfit/ui/components/selector/MealOccasionSelector.kt

PR [1/n]
Selector to choose a meal occasion and update the value using a callback. First of a few PRs for the additional info UI to keep things small.

Meal Occasion Selector

---

app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/DateSelectorScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/DateSelectorTest.kt
app/src/main/java/com/github/se/polyfit/ui/components/selector/DateSelector.kt

PR [2/n]
Selector to choose a date and update the value using a callback. Second of a few PRs for the additional info UI to keep things small.

Date Selector

---

app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealTagSelectorScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealTagSelectorTest.kt
app/src/main/java/com/github/se/polyfit/ui/components/ColorTable.kt
app/src/main/java/com/github/se/polyfit/ui/components/MealTagList.kt
app/src/main/java/com/github/se/polyfit/ui/components/dialog/MealTagDialog.kt
app/src/main/java/com/github/se/polyfit/ui/components/selector/MealTagSelector.kt

PR [3/n]
Selector to add/edit meal tags using a callback. Third of a few PRs for the additional info UI to keep things small.

Meal Tag Selector

---

app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt
app/src/main/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformation.kt
app/src/test/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformationTest.kt

Nutrient searching should not care about case sensitivity.

Ignore case for nutrient searching

---

app/src/androidTest/java/com/github/se/polyfit/ui/screen/OverviewScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/OverviewScreenTest.kt
app/src/main/java/com/github/se/polyfit/MainActivity.kt
app/src/main/java/com/github/se/polyfit/ui/components/selector/MealSelector.kt
app/src/main/java/com/github/se/polyfit/ui/navigation/Navigation.kt
app/src/main/java/com/github/se/polyfit/ui/navigation/Route.kt
app/src/main/java/com/github/se/polyfit/ui/screen/OverviewScreen.kt

Since we don't have designs for this yet, putting a temporary way to get to the CreatePostScreen that we can change after M2.

Temporary access to create post

---

app/src/main/java/com/github/se/polyfit/ui/components/postinfo/Text.kt

fix not show every nutrient but only 3 principals

---

.github/workflows/apkPipeline.yml
app/build.gradle.kts
app/src/androidTest/java/com/github/se/polyfit/viewmodel/MealViewModelTest.kt
app/src/main/java/com/github/se/polyfit/ui/components/scaffold/BottomNavigation.kt
app/src/main/java/com/github/se/polyfit/ui/screen/GraphScreen.kt
app/src/main/java/com/github/se/polyfit/viewmodel/meal/MealViewModel.kt
app/src/main/java/com/github/se/polyfit/viewmodel/post/CreatePostViewModel.kt

This PR addresses instability issues in the APK due to two primary factors:
The use of `isMinifyEnabled = true` in our Kotlin configuration is intended to enhance app security by reducing the possibility of control-flow attacks. However, this setting seems as a contributing factor to issues during APK generation.
The `CreateViewModel` was previously executing database calls directly on the main thread, leading to application freezes and crashes. This process has been modified to use the IO dispatcher, thereby ensuring operations do not block the main thread and improve app stability.
Issue with the icon on the bottom bar not being selected when on the  post info screen.

Unstable apk

---

.github/workflows/apkPipeline.yml

Quick fix to avoid release conflicts with the same names.

Apk release naming

---

app/src/androidTest/java/com/github/se/polyfit/ui/screen/SettingScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/SettingsScreen.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/SettingsTest.kt
app/src/main/java/com/github/se/polyfit/model/settings/SettingOption.kt
app/src/main/java/com/github/se/polyfit/ui/components/scaffold/BottomNavigation.kt
app/src/main/java/com/github/se/polyfit/ui/screen/SettingsScreen.kt
app/src/main/res/values/strings.xml

This is the UI for the main settings screen. From here, people will be able to navigate to specific setting pages. Those pages will be made in following PRs so everything is small.

Main Setting Screen

---

app/src/androidTest/java/com/github/se/polyfit/data/remote/firebase/UserFirebaseRepositoryTest.kt
app/src/main/java/com/github/se/polyfit/data/remote/firebase/UserFirebaseRepository.kt
app/src/main/java/com/github/se/polyfit/di/UserModule.kt
app/src/main/java/com/github/se/polyfit/model/user/User.kt
app/src/main/java/com/github/se/polyfit/ui/hiltModule/AuthModule.kt
app/src/main/java/com/github/se/polyfit/ui/utils/Authentication.kt
app/src/test/java/com/github/se/polyfit/data/user/UserAuthTest.kt
app/src/test/java/com/github/se/polyfit/data/user/UserTest.kt

In order to make the UI to update users information (weight, height, etc...), first we need to store our users information in firebase. Then, we will be able to use this information to fill out the fields and update them accordingly

Store user information in firebase

---

app/src/main/java/com/github/se/polyfit/model/user/User.kt
app/src/main/java/com/github/se/polyfit/ui/utils/Authentication.kt

PR #252 was merged before a reviewer completed, so here are the changes. Please see the other PR for the comments and answers

Charles PR comments addressed

---

app/src/main/java/com/github/se/polyfit/ui/theme/Theme.kt

As the coach said, we can remove the dark mode. Way easier than updating all the application to work on dark-mode

Remove the dark mode because we don't have one for the moment.

---

app/src/androidTest/java/com/github/se/polyfit/end2end/EndTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/flow/AddMealFlowTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/OverviewScreenTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/SelectIngredientsScreen.kt
app/src/main/java/com/github/se/polyfit/ui/screen/IngredientScreen.kt

User shouldn't be able to go to next step of meal creation without adding ingredients

Ingredient button disables until ingredient is added

---

app/src/androidTest/java/com/github/se/polyfit/data/processor/LocalDataProcessorTest.kt
app/src/androidTest/java/com/github/se/polyfit/end2end/EndTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/OverviewScreenTest.kt
app/src/androidTest/java/com/github/se/polyfit/viewmodel/MealViewModelTest.kt
app/src/androidTest/java/com/github/se/polyfit/viewmodel/post/ViewPostViewModelTest.kt
app/src/main/java/com/github/se/polyfit/data/local/dao/MealDao.kt
app/src/main/java/com/github/se/polyfit/data/processor/LocalDataProcessor.kt
app/src/main/java/com/github/se/polyfit/ui/components/card/MealTrackerCard.kt
app/src/main/java/com/github/se/polyfit/ui/screen/OverviewScreen.kt
app/src/main/java/com/github/se/polyfit/viewmodel/meal/OverviewViewModel.kt
app/src/test/java/com/github/se/polyfit/viewmodel/meal/OverviewViewModelTest.kt

The values for the daily summary of calories consumed for each meal were hardcoded instead of being fetched from the local database. This issue also affected the calorie goals.

OverviewScreen daily calories not being displayed correctly

---

app/src/androidTest/java/com/github/se/polyfit/data/processor/LocalDataProcessorTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/CreatePostTest.kt
app/src/main/java/com/github/se/polyfit/MainActivity.kt
app/src/main/java/com/github/se/polyfit/data/local/dao/MealDao.kt
app/src/main/java/com/github/se/polyfit/data/processor/LocalDataProcessor.kt
app/src/main/java/com/github/se/polyfit/ui/components/scaffold/CenteredTopBar.kt
app/src/main/java/com/github/se/polyfit/ui/components/scaffold/SimpleTopBar.kt
app/src/main/java/com/github/se/polyfit/ui/navigation/Navigation.kt
app/src/main/java/com/github/se/polyfit/ui/screen/IngredientScreen.kt
app/src/main/java/com/github/se/polyfit/ui/screen/NutritionScreen.kt
app/src/test/java/com/github/se/polyfit/ui/navigation/NavigationTest.kt

A small issue occurred when the user clicked twice on the back arrow in some screens before the screen could be updated with the new UI. This was caused by the `NavHostController` being `popBackStack()` twice instead of once. This is resolved by allowing only the first click to be registered before navigating to the new screen.

Issue with clicking twice on the back arrow

---

app/schemas/com.github.se.polyfit.data.local.database.MealDatabase/4.json
app/src/androidTest/java/com/github/se/polyfit/data/local/database/MealDatabaseTest.kt
app/src/androidTest/java/com/github/se/polyfit/data/processor/LocalDataProcessorTest.kt
app/src/androidTest/java/com/github/se/polyfit/data/repository/MealRepositoryTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/nutrition/NutritionalInformationTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealSelectorTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/components/textField/MealInputTextFieldTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/flow/AddMealFlowTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/CreatePostTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt
app/src/androidTest/java/com/github/se/polyfit/ui/screen/NutritionalInformationTest.kt
app/src/androidTest/java/com/github/se/polyfit/viewmodel/MealViewModelTest.kt
app/src/androidTest/java/com/github/se/polyfit/viewmodel/meal/OverviewViewModelTest.kt
app/src/main/java/com/github/se/polyfit/data/local/dao/MealDao.kt
app/src/main/java/com/github/se/polyfit/data/local/database/MealDatabase.kt
app/src/main/java/com/github/se/polyfit/data/local/entity/MealEntity.kt
app/src/main/java/com/github/se/polyfit/data/processor/LocalDataProcessor.kt
app/src/main/java/com/github/se/polyfit/data/repository/MealRepository.kt
app/src/main/java/com/github/se/polyfit/di/UserModule.kt
app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt
app/src/main/java/com/github/se/polyfit/viewmodel/meal/MealViewModel.kt
app/src/main/java/com/github/se/polyfit/viewmodel/meal/OverviewViewModel.kt

Update the `Meal` class to have a `userId` to prevent issues when a different user logs in and our database stores multi-user info. This will allow us to call `getAllMeals()` and other meal queries with a injected parameters of userId, to only return meals relevant to the logged in user.
<hr>
I've ran a migration script on our Firebase user database to backfill all the meals to include the userId, and also for our posts. I'll run it again after merge. Here's the scripts I used:
$$\quad$$
```js
const admin = require('firebase-admin');
const serviceAccount = require('./myPrivateKey');  // downloaded from firebase
admin.initializeApp({
credential: admin.credential.cert(serviceAccount),
databaseURL: 'https://<your-database-name>.firebaseio.com' // copy real from firebase
});
const db = …
```

Add userId to meals

---

app/src/main/java/com/github/se/polyfit/ui/components/button/PrimaryButton.kt

Changed our logic for disabling buttons to temporarily disable it rather than permanently

Use LaunchedEffect to disable button temporarily
