swent-group10/polyfit

app/src/androidTest/java/com/github/se/polyfit/ui/components/NutritionalInformationScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/NutritionalInformationTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/NutritionalInformationScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/NutritionalInformationTest.kt, app/src/main/java/com/github/se/polyfit/model/nutritionalInformation/Nutrient.kt, app/src/main/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformation.kt, app/src/main/java/com/github/se/polyfit/ui/components/NutritionalInformation.kt, app/src/main/java/com/github/se/polyfit/ui/screen/IngredientScreen.kt, app/src/main/java/com/github/se/polyfit/ui/screen/NutritionScreen.kt, app/src/main/java/com/github/se/polyfit/ui/utils/StringUtils.kt, app/src/test/java/com/github/se/polyfit/model/nutritionalInformation/NutrientTest.kt, app/src/test/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformationTest.kt, app/src/test/java/com/github/se/polyfit/ui/utils/StringUtilsTest.kt
Adding UI support to [display nutritional information](https://github.com/orgs/swent-group10/projects/2?pane=issue&itemId=57702252).
- Takes in a Meal, and displays the title and nutrition facts for all ingredients. 
- Buttons to save to diary or add recipe, easy to hookup when that functionality is ready
- no title editing for now, but also easy to add when we are ready to support that functionality
=> Nutritional Information Screen

app/src/androidTest/java/com/github/se/polyfit/ui/screen/LoginTest.kt
This pull request addresses a failing test case in the `LoginTest` class, specifically the `googleSignInReturnsValidActivityResult` test. The test was failing due to an `IllegalStateException` indicating that no compose hierarchies were found in the app.
The test failed with an `IllegalStateException`, suggesting issues with `setContent` related operations. It was determined that conditions were not properly initialized, and Compose UI elements were not stabilized before the test ran.
The issue has been resolved by implementing a waiting mechanism that ensures all elements are stabilized before the test is executed.
=> Fixes issues with checking if login intent was sent

app/src/androidTest/java/com/github/se/polyfit/ui/screen/LoginTest.kt
This pull request addresses a failing test case in the `LoginTest` class, specifically the `googleSignInReturnsValidActivityResult` test. The test was failing due to an `IllegalStateException` indicating that no compose hierarchies were found in the app.
The test failed with an `IllegalStateException`, suggesting issues with `setContent` related operations. It was determined that conditions were not properly initialized, and Compose UI elements were not stabilized before the test ran.
The issue has been resolved by implementing a waiting mechanism that ensures all elements are stabilized before the test is executed.
It turns out the issue was due to incorrect initialization of the intents in the test. To ensure more consistent testing, the intents are now mocked.
=> authentication test failing

.github/workflows/apkPipeline.yml, .github/workflows/ci.yml
- Due to a change in the project, when compiling, Gradle checks a local file for API keys. However, this was not taken into account in the previous iteration of the APK (#65) and the CI. The PR addresses this by creating a new local file during compilation and adds the API keys.
=> Issue with Spoonacular API keys when compilling apk and ci pipeline

app/src/main/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformation.kt, app/src/test/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformationTest.kt
https://github.com/swent-group10/polyfit/issues/95
Quick PR to prevent Nutritional Information from having negative values. I decided it would be ok to leave the `Nutrient` if it is zero because it is helpful to see that there is no amount of a nutrient visually.
=> FIX: Ensuring no negative nutrients in NutritionalInfo

app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt, app/src/test/java/com/github/se/polyfit/model/meal/MealTest.kt
To show meals of any given day in the overview screen, add a `createdAt` field to our `Meal` so we know which day it belongs.
Ticket: https://github.com/swent-group10/polyfit/issues/99
Confirmation that it uploaded to Firebase:
=> Store date of meal creation in DB

app/src/main/java/com/github/se/polyfit/model/meal/MealTag.kt
More pastel colors make tags more visible.
=> Change tags' color to more be pastel

app/src/androidTest/java/com/github/se/polyfit/ui/screen/OverviewScreenTest.kt, app/src/main/java/com/github/se/polyfit/ui/screen/IngredientScreen.kt, app/src/main/java/com/github/se/polyfit/ui/screen/OverviewScreen.kt, app/src/main/java/com/github/se/polyfit/viewmodel/meal/MealViewModel.kt
Allow users to create a meal without taking a picture. 
I took the MealViewModel out of the main activity at least and brought it to our main nav graph as it didn't need to be such a high level. Ideally when we can pass around ids rather than mealViewModel, we can get rid of the need to reset it.
=> Create Meal without a Photo

app/src/androidTest/java/com/github/se/polyfit/ui/components/nutrition/NutritionalInformationTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/flow/AddMealFlowTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/OverviewScreenTest.kt, app/src/androidTest/java/com/github/se/polyfit/viewmodel/MealViewModelTest.kt, app/src/main/java/com/github/se/polyfit/MainActivity.kt, app/src/main/java/com/github/se/polyfit/model/ingredient/Ingredient.kt, app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt, app/src/main/java/com/github/se/polyfit/ui/flow/AddMealFlow.kt, app/src/main/java/com/github/se/polyfit/ui/screen/AdditionalMealInfoScreen.kt, app/src/main/java/com/github/se/polyfit/ui/screen/NutritionScreen.kt, app/src/main/java/com/github/se/polyfit/viewmodel/meal/MealViewModel.kt
Fixing bugs within the AddMeal flow:
- Nutrients are not reflecting properly. It's because every time we copy a meal, we copy the nutritional value and then add the ingredient nutrients, which double counts. The fix was to use a `deepCopy` with an empty NutritionalInformation object, so it reflects only the ingredients in the copied meal.
- Meal Occasion not showing up even when selected. This was because we were setting `initial = Meal.default()` on this page, even though it should have a value already. Removing this fixes that.
- Tags disappearing: MealViewModel's updateMealData didn't include the tags, so it removed them every time it got called to a default empty list.
- UserId is not used at all in the AddMealFlow, so removed
**Take away / advice**: When creating a Meal, never set …
=> Bugfix: MealViewModel Mistakes

app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt, app/src/test/java/com/github/se/polyfit/model/meal/MealTest.kt
We're having issues with double counting nutrients. This is a temp fix before M2 to prevent meals with nutritional information from getting updated in construction. It will be changed later to prevent allowing nutritional information to be passed as a parameter.
See https://github.com/swent-group10/polyfit/issues/177
=> BUGFIX: Only update nutritional information if empty

app/src/androidTest/java/com/github/se/polyfit/ui/components/dialog/LocationPermissionScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/dialog/LocationPermissionTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealSelectorScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealSelectorTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/textField/MealInputTextFieldScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/textField/MealInputTextFieldTest.kt, app/src/androidTest/java/com/github/se/polyfit/viewmodel/post/CreatePostViewModelTest.kt, app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt, app/src/main/java/com/github/se/polyfit/model/post/Post.kt, app/src/main/java/com/github/se/polyfit/ui/components/dialog/LocationPermissionDialog.kt, app/src/main/java/com/github/se/polyfit/ui/components/scaffold/CenteredTopBar.kt, app/src/main/java/com/github/se/polyfit/ui/components/selector/MealSelector.kt, app/src/main/java/com/github/se/polyfit/ui/components/selector/PictureSelector.kt, app/src/main/java/com/github/se/polyfit/ui/components/textField/MealInputTextField.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/github/se/polyfit/data/post/PostTest.kt
These are the helper components for UI of making a new post for others to see. (see #158 for final look of screen.)
Components:
- Picture selector for picking a picture for the post (only a place holder now as we do not yet know if backend will be able to support image for posts)
- Textfield for post description input
- Meal selector for picking a meal for the post
- Meal Details for displaying details of the meal selected for the post
- Alert Dialog for asking for use permission to use their location
=> UI/ Helpers for CreatePostScreen

.github/workflows/apkPipeline.yml, gradle.properties
Really simple fix consisting of modifying the `gradle.properties` to increase the max memory usage.
=> APK compillation error caused by not enought memory 

app/src/androidTest/java/com/github/se/polyfit/data/local/database/MealDatabaseTest.kt, app/src/androidTest/java/com/github/se/polyfit/data/remote/firebase/MealFirebaseRepositoryTest.kt, app/src/androidTest/java/com/github/se/polyfit/data/repository/MealRepositoryTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/list/MealListTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/nutrition/NutritionalInformationTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealSelectorTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/components/textField/MealInputTextFieldTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/CreatePostTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/DailyRecapTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/NutritionalInformationTest.kt, app/src/androidTest/java/com/github/se/polyfit/viewmodel/MealViewModelTest.kt, app/src/androidTest/java/com/github/se/polyfit/viewmodel/dailyRecap/DailyRecapViewModelTest.kt, app/src/androidTest/java/com/github/se/polyfit/viewmodel/post/CreatePostViewModelTest.kt, app/src/main/java/com/github/se/polyfit/data/api/SpoonacularAPI.kt, app/src/main/java/com/github/se/polyfit/data/local/entity/MealEntity.kt, app/src/main/java/com/github/se/polyfit/model/ingredient/Ingredient.kt, app/src/main/java/com/github/se/polyfit/model/meal/Meal.kt, app/src/main/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformation.kt, app/src/main/java/com/github/se/polyfit/viewmodel/meal/MealViewModel.kt, app/src/test/java/com/github/se/polyfit/data/processor/LocalDataProcessorTest.kt, app/src/test/java/com/github/se/polyfit/model/ingredient/IngredientTest.kt, app/src/test/java/com/github/se/polyfit/model/meal/MealTest.kt, app/src/test/java/com/github/se/polyfit/model/nutritionalInformation/NutritionalInformationTest.kt, app/src/test/java/com/github/se/polyfit/viewmodel/meal/OverviewViewModelTest.kt
This PR is the first pass of this task - `NutritionalInformation` is removed from the `Meal` constructor parameters and calculated during construction from the ingredients. As a safeguard, it is accessible publicly but only able to be set internally. We can remove the `deepCopy` function as regular copying should now properly calculate nutrition.
The second pass after the cleanup (not required, but could be a good idea) is to run a database migration to drop the `nutritionalInformation` column. I will do this in a following PR since it will be easier to do once the cleanup is finished.
A lot of this code is deleting `NutritionalInformation` from `Meal` constructors in tests and moving it into ingredients (if needed for that test) so that the functionality of all the tests is preserved. …
=> Remove NutritionalInformation from Meal constructor

app/src/androidTest/java/com/github/se/polyfit/ui/flow/SettingFlowTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/navigation/NavigationTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/settings/AccountSettingsScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/settings/AccountSettingsTest.kt, app/src/androidTest/java/com/github/se/polyfit/viewmodel/settings/AccountSettingsViewModelTest.kt, app/src/main/java/com/github/se/polyfit/MainActivity.kt, app/src/main/java/com/github/se/polyfit/model/user/User.kt, app/src/main/java/com/github/se/polyfit/ui/components/GenericScreen.kt, app/src/main/java/com/github/se/polyfit/ui/components/selector/DateSelector.kt, app/src/main/java/com/github/se/polyfit/ui/flow/SettingFlow.kt, app/src/main/java/com/github/se/polyfit/ui/navigation/Navigation.kt, app/src/main/java/com/github/se/polyfit/ui/navigation/Route.kt, app/src/main/java/com/github/se/polyfit/ui/screen/settings/AccountSettingsScreen.kt, app/src/main/java/com/github/se/polyfit/viewmodel/settings/AccountSettingsViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/github/se/polyfit/data/user/UserTest.kt
UI, Viewmodel, tests for Account Settings. It is fully integrated with backend.
On this screen, Users can edit the information we have about them. The name fields are mandatory, and the rest is optional (since this stuff needs to be edited by the user because we don't get it from firebase). It is integrated with the bottom navigation bar and the main setting screen.
I haven't yet added the UI/sliders for the dietary restrictions because of time constraint, but I think this will be sufficient for M3 and then will add those in M4. The backend is setup for them already
=> Account Settings

app/src/androidTest/java/com/github/se/polyfit/ui/components/button/PrimaryButtonTest.kt, app/src/main/java/com/github/se/polyfit/ui/components/button/PrimaryButton.kt
Only run the onClick of the primary button once, to prevent unexpected side-effects of spam
=> Prevent PrimaryButton double clicks

app/src/androidTest/java/com/github/se/polyfit/ui/components/ingredients/IngredientNutritionEditFieldsTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/flow/AddMealFlowTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt, app/src/main/java/com/github/se/polyfit/ui/components/ingredients/IngredientNutritionEditFields.kt
Now, when you type `1` it will say `1.0` instead of `10.0`. Also, as soon as you type it, the button will activate.
=> Fix issues with editing ingredient info

app/src/main/java/com/github/se/polyfit/ui/screen/settings/AccountSettingsScreen.kt
So that the keyboard doesn't cover the bottom of the settings, make it a lazy column. Tested with a smaller sized emulator:
=> Use lazy column for settings so it doesn't get blocked

app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
This PR fixes an issue where part of the first post was hidden in the UI where all the posts are displayed. This was due to the misuse of padding.
| Before | After |
|--------|-------|
| ![image](https://github.com/swent-group10/polyfit/assets/100274930/a0cd6855-7c02-48b4-a628-43ee1bf2c571) | ![image](https://github.com/swent-group10/polyfit/assets/100274930/5cfadb33-779b-4471-91e2-781f55a8fc64) |
=> Issue with padding in the PostView screen

app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealSelectorTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/CreateAPostScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/CreatePostTest.kt, app/src/main/java/com/github/se/polyfit/MainActivity.kt, app/src/main/java/com/github/se/polyfit/ui/components/selector/MealSelector.kt, app/src/main/java/com/github/se/polyfit/ui/screen/CreatePostScreen.kt, app/src/main/res/values/strings.xml
When making a post, if you have no meals it will bring you to the create post screen and you won't be able to select anything. Instead, let's show a helpful message that directs users to add a meal. Also small fix is to round the calories to two decimals to fix formatting display issue
=> Show a helpful message when posting if there are no meals

app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealSelectorTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/GraphScreenTest.kt, app/src/main/java/com/github/se/polyfit/model/nutritionalInformation/MeasurementUnit.kt, app/src/main/java/com/github/se/polyfit/ui/screen/GraphScreen.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/github/se/polyfit/model/nutritionalInformation/MeasurementUnitTest.kt
Fixing small bug that caused number of calories or weight with big decimal to make the app crash when attempted to be displayed
=> bugfix, bumping the display of graph elements to 2 decimal points

app/src/main/java/com/github/se/polyfit/ui/components/selector/DateSelector.kt, app/src/main/java/com/github/se/polyfit/ui/screen/settings/AccountSettingsScreen.kt
From the feedback we received in Sprint 9 retro, we should block users from setting birthdays in the future.
I added an extra default parameter to the date selector such that if the user passes the non-default value, users can not select a date in the future.
=> Prevent users from having their birthday set in the future

app/src/main/java/com/github/se/polyfit/ui/components/selector/MealSelector.kt
When making a post, if the screen is too small the circle gets squished
Before:
Results:
=> Fix the squished circle for nutrients

app/src/main/java/com/github/se/polyfit/ui/screen/settings/AccountSettingsScreen.kt
**Issue:** When the user chooses a large username, it affects the placement of the composable on the overview screen and can sometimes cause the app to crash.
**Resolution:** To fix this, the username is now set to have a maximum of 20 characters.
=> Large username causes the app to crash

app/src/main/java/com/github/se/polyfit/ui/screen/CreatePostScreen.kt
As you can see in the before and after, instead of a new line the enter button is now a checkmark to close the keyboard.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Make the description for post creation close on enter press

app/src/androidTest/java/com/github/se/polyfit/ui/flow/AddMealFlowTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/IngredientTest.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/NutritionalInformationScreen.kt, app/src/androidTest/java/com/github/se/polyfit/ui/screen/SelectIngredientsScreen.kt, app/src/main/java/com/github/se/polyfit/ui/components/scaffold/SimpleTopBar.kt, app/src/main/java/com/github/se/polyfit/ui/flow/AddMealFlow.kt, app/src/main/java/com/github/se/polyfit/ui/screen/IngredientScreen.kt, app/src/main/java/com/github/se/polyfit/ui/screen/NutritionScreen.kt, app/src/main/res/values/strings.xml
In this PR, I added a confirmation when leaving `AddMealFlow`. I had to change how we disable the back button on the top bar in this file so that it can be pressed more than once, and also cleaned up the other top bars to be standardized.
=> Warning when leaving Add Meal

app/src/main/java/com/github/se/polyfit/ui/components/list/MealTagList.kt
Our mealtag onclick was empty on the daily recap, making the button clickable with no effect. This overrode the outer onclick for the whole meal to go and edit it. This fix addresses that issue, removing the onclick from the meal tag if it is display only.
=> Adjust the MealTag onclick

app/src/androidTest/java/com/github/se/polyfit/ui/components/selector/MealTagSelectorTest.kt, app/src/main/java/com/github/se/polyfit/ui/components/dialog/MealTagDialog.kt
To prevent users dumping data into our DB, limit the input on meal tags to 50 chars
=> Limit tag length to 50 chars
